# Generated by Django 4.1 on 2023-09-02 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='theCustomer',
        ),
    ]
