# Generated by Django 4.1 on 2023-09-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0002_rename_basket_thecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='theCustomer',
        ),
    ]
